---
# tasks file for nginx_php_fpm
- name: Install Nginx
  apt:
    name: nginx
    state: latest
- name: install Php-fpm
  apt: 
    name: php7.0-fpm
    state: latest
- name: Configuration server
  copy:
    src: /home/vladimir/SkillFactory/ansible/roles/nginx_php_fpm/files/192.168.1.113.cfg
    dest: /etc/nginx/sites-available/192.168.1.113
- name: Remove default config from sites-enabled
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
- name: ceate symlink
  file:
    src: /etc/nginx/sites-available/192.168.1.113
    dest: /etc/nginx/sites-enabled/192.168.1.113
    state: link
- name: Create index.php
  copy:
    src: /home/vladimir/SkillFactory/ansible/roles/nginx_php_fpm/files/index.php
    dest: /var/www/html/index.php
  notify:
  - Restart nginx
  - Restart fpm

- name: Change root direcory
  lineinfile:
    path: /etc/nginx/sites-available/192.168.1.113
    regexp: 'root /var/www/html;'
    line: '    root /opt/nginx/ansible;'
    backrefs: yes

- name: Create directory nginx
  file:
    path: /opt/nginx
    state: directory
- name: Create directory ansible
  file:
    path: /opt/nginx/ansible
    state: directory
- name: Create new index file
  copy:
    src: /home/vladimir/SkillFactory/ansible/roles/nginx_php_fpm_handler/files/index_new.php
    dest: /opt/nginx/ansible/index.php
  notify:
  - Restart nginx
  - Restart fpm
