---
# tasks file for vsftpd
- name: install vsftpd
  apt:
    name: vsftpd
    state: latest
- name: Configuration vsftpd
  copy:
    src: /home/vladimir/SkillFactory/ansible/roles/vsftpd/files/vsftpd.conf
    dest: /etc/vsftpd.conf
- name: start service
  service:
    name: vsftpd
    state: started
    enabled: yes
